### ISSUE TITLE
Icon sizes

### ISSUE THREAD

**Issue by azu** [textlint/media#2]
Curently, put one size per icons.
- icon-black-and-white.png
- icon-grayscale.png
- icon.png

We'll put various size per icons maybe.
This approch is similar to [alrra/browser-logos](https://github.com/alrra/browser-logos). 
- 16x16.png
- ...
- 512x512.png

Deploy these files to `gh-pages` branch and show directly this via URL like http://textlint.github.io/media/icon/icon.png

**Comment by uetchy** [comment]
I'm on it

**Comment by uetchy** [comment]
<img width="450" alt="screen shot 2016-01-29 at 22 16 31" src="https://cloud.githubusercontent.com/assets/431808/12676484/041e70ac-c6d6-11e5-9f95-ba3898a0e001.png">

Thanks to Sketch, this is not particularly difficult.

**Comment by azu** [comment]
closed by #3
